<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/Groupby_%26_Date.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Groupby ()
import pandas as pd
sam = pd.read_csv('/content/sample_data/california_housing_train.csv')
sam.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [4]:
sam.groupby('housing_median_age').mean()['median_house_value']

housing_median_age
1.0     190250.000000
2.0     229438.836735
3.0     239450.043478
4.0     230054.105590
5.0     211035.708543
6.0     206768.240310
7.0     188445.059603
8.0     190805.073034
9.0     190306.994186
10.0    178416.393805
11.0    182480.312500
12.0    181590.640625
13.0    188065.473896
14.0    191181.288184
15.0    181031.024038
16.0    200354.507087
17.0    191772.244792
18.0    192074.715481
19.0    196017.752427
20.0    192681.751958
21.0    200918.536193
22.0    213129.173375
23.0    204621.787958
24.0    207293.365039
25.0    223097.223427
26.0    206773.793241
27.0    206728.259446
28.0    210049.812500
29.0    195185.863636
30.0    201559.145833
31.0    208319.851562
32.0    207131.500000
33.0    203922.269006
34.0    213061.615520
35.0    205624.462428
36.0    208262.422378
37.0    209008.299771
38.0    195272.371069
39.0    206718.913907
40.0    205783.594378
41.0    197328.935345
42.0    199635.110390
43.0    194365.779720
44.0    214909.506757
45.0    223464.744681
46.0    198036.260204
47.0    190064.611429
48.0    224665.251852
49.0    220667.612613
50.0    222513.482143
51.0    244850.125000
52.0    277368.200570
Name: median_house_value, dtype: float64

In [5]:
#Pandas Date Range - Days frequency
pd.date_range(start='1/1/2018', end='1/08/2018')

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

In [8]:
#Months frequency
pd.date_range(start='2022-02-01', end='2022-10-01', freq='ME')

DatetimeIndex(['2022-02-28', '2022-03-31', '2022-04-30', '2022-05-31',
               '2022-06-30', '2022-07-31', '2022-08-31', '2022-09-30'],
              dtype='datetime64[ns]', freq='ME')

In [9]:
#Weekdays frequency
pd.date_range(start='2022-02-01', end='2022-02-10', freq='B')

DatetimeIndex(['2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
               '2022-02-07', '2022-02-08', '2022-02-09', '2022-02-10'],
              dtype='datetime64[ns]', freq='B')